application: hringfari-geogebra
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt
  
- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
  
- url: /media
  static_dir: media

- url: /.*
  script: djangoappengine/main/main.py
